name: Actualizar RSS de Naturgy

on:
  workflow_dispatch:
  schedule:
    - cron: "53 * * * *"

permissions:
  contents: write

jobs:
  actualizar-rss:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Crear RSS
        run: python rss.py

      - name: Guardar RSS actualizada
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git diff --cached --quiet || git commit -m "Actualizar RSS de Naturgy"
          git push
